name: tico_apps
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.12.0
  cloud_firestore: ^0.14.0
  equatable: ^0.2.0
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  flutter_bloc: ^0.11.0
  flutter_svg: ^0.19.0
  flutter_form_builder: ^4.2.0
  font_awesome_flutter: ^8.4.0
  flutter_datetime_picker: ^1.5.0
  get: ^3.26.0
  get_it: ^4.0.1
  google_sign_in: ^4.0.1
  injectable: ^0.3.0
  json_annotation: ^3.0.1
  meta: ^1.1.6
  modal_bottom_sheet: ^1.0.0
  provider: ^4.3.3
  rxdart: ^0.21.0
  shimmer: ^1.1.2
  shared_preferences: ^0.5.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
